## Numpy Array Basics: 
- pre-assigned values 
- zeroes
- ones
- range of values
- linspace 

In [1]:
list_1 = [1,2,3]
print(list_1)

[1, 2, 3]


In [2]:
import numpy as np

### Pass in pre-made list to array
np.array(list)

In [3]:
numpy_1 = np.array(list_1)
print(numpy_1)

[1 2 3]


### Create arrays of zeroes and ones 
np.zeroes(desired length) Note: Yes it's spelled this way <br>
np.ones(desired length) <br>

In [4]:
#Create array of zeroes. Takes in desired length as input 
zeroes_array = np.zeros(5)
print(zeroes_array)

[0. 0. 0. 0. 0.]


In [5]:
#Create array of ones. Take in desired length as input 
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Create ranges in array
np.arange(#,#) Note:(#,#] <br>


In [6]:
# Create a range in an array. Goes from (0,inclusive] 
range_array_1 = np.arange(5)
print(range_array_1)

[0 1 2 3 4]


In [7]:
# Specifying the starting point
range_array_2 = np.arange(5,11)
print(range_array_2)

[ 5  6  7  8  9 10]


In [8]:
# Create an interval that you want the range to increment by
range_array_3 = np.arange(0, 20, 2)
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18]


### Use step intervals (linspace)
np.linspace(lower bound, upper bound, # of elements between bounds) <br>Note: upper bound is inclusive 

In [9]:
# linspace = linear space
# Takes a lower bound, upper bound, and # of elements in between these boundaries
# The uppper bound is inclusive in linspace
# Automatically spaces the number of elements evenly between the boundaries
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
linspace_array_1 = np.linspace(0,10,) # Default is 50
print(linspace_array_1)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
