## Number of functions to get:
- elements based on index
- slices arrays
- access ranges
- get length of array
- get max, min, average of the arrays

In [1]:
import numpy as np

In [4]:
#create an array
an_array = np.arange(0, 11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Accessing a single index
Note: Must check arrays manually in JN, as they do not check for ArrayOutOfBounds

In [5]:
#First element of array
first_element = an_array[0]
print(first_element)

0


In [6]:
#Last element of array
last_element = an_array[len(an_array)-1]
print(last_element)

10


### Accessing multiple indices/slices
Note: Range is not inclusive (0,#] 


In [8]:
#Note: Range is not inclusive 
first_five = an_array[0:5]
print(first_five)

[0 1 2 3 4]


In [9]:
#Print first five array elements
first_five_1 = an_array[:5]
print(first_five_1)

[0 1 2 3 4]


In [10]:
#Print last five elements
last_five = an_array[6:]
print(last_five)

[ 6  7  8  9 10]


In [11]:
#Increment by 2 
last_five_incr_2 = an_array[6::2]
print(last_five_incr_2)

[ 6  8 10]


In [13]:
# Decrement by 1. 
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [15]:
# Printing out the last two elements of array (without using length of the array)
final_two = an_array[-2:]
print(final_two)

[ 9 10]


### Get the length of an array

In [16]:
print(an_array.size)

11


### Calculate Max, Min and Average of an Array

In [18]:
#Calculate max
print(np.amax(an_array))

10


In [19]:
#Calculate min 
print(np.amin(an_array))

0


In [20]:
#Calculate average 
print(np.average(an_array))

5.0
