## Intro to matrices in numpy
- Talk about what matrices are and why they're important
- Create a custom matrix
- Create a matrix of ones or zeros

### What is a matrix?
**Matrix**: a multidimensional array
- an array of arrays
- used in images, geological data, ML and anything graph related

An image of a 1 might look like:<br>
[[0, 0, 1, 0, 0], <br>
 &nbsp;[0, 0, 1, 0, 0], <br>
 &nbsp;[0, 0, 1, 0, 0], <br>
 &nbsp;[0, 0, 1, 0, 0], <br>
 &nbsp;[0, 0, 1, 0, 0]] <br>
 Note that quite literally, there is a '1' seen on the image. 

In [7]:
import numpy as np 

### Create a custom matrix

In [8]:
two_by_two = np.matrix([[1,2],[3,4]]) 
print(two_by_two)

[[1 2]
 [3 4]]


In [9]:
two_by_three = np.matrix('1 2; 3 4; 5 6')
print(two_by_three)

[[1 2]
 [3 4]
 [5 6]]


### Zeroes Matrices

In [10]:
print(np.zeros([3, 2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones matrices

In [11]:
print(np.ones([2, 4]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
