# Operations to change elements or properties
- Change individual elements or rows
- Sort matrices
- Transpose matrices
- Multiplication and addition
- Matrix Multiplication

In [2]:
import numpy as np

In [4]:
#Set up your matrix
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix)

[[1 2]
 [3 4]]


### Change individual elements or rows

In [5]:
#Set the second row, index 0th position as 10
a_matrix[1,0] = 10
print(a_matrix)

[[ 1  2]
 [10  4]]


In [6]:
#Set the 0th row as [6,3]
a_matrix[0] = [6, 3]
print(a_matrix)

[[ 6  3]
 [10  4]]


### Sort matrices
Sorting works on individual rows. Rows retain their order but the elements in the row will be sorted. 
<br><br>
np.sort(matrix_name)

In [7]:
#Sort each row in ascending order
print(np.sort(a_matrix))

[[ 3  6]
 [ 4 10]]


In [8]:
# Sort each row in descending order
print(-np.sort(-a_matrix))

[[ 6  3]
 [10  4]]


### Transpose matrices 
**tranpose**: matrix_name.T <br> 
**flatten**: matrix_name.flatten()

In [9]:
#Tranpose: rows become columns 
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix.T)

[[1 3]
 [2 4]]


In [10]:
#Flatten the matrix into a 1xn matrix. 
print(a_matrix.flatten())

[[1 2 3 4]]


### Multiplication and addition
Function is applied to each element in the matrix

In [11]:
#Add one to each element 
print(a_matrix + 1)

[[2 3]
 [4 5]]


In [12]:
#Multiply each element by 2 
print(a_matrix * 2)

[[2 4]
 [6 8]]


Append matrices together. They must be of the same size. 

In [13]:
print(np.add(a_matrix, a_matrix))

[[2 4]
 [6 8]]


### Matrix Multiplication
**matrix multiplication**: np.matmul(matrix1,matrix2)

In [14]:
print(np.matmul(a_matrix, a_matrix))

[[ 7 10]
 [15 22]]
