# Example of Matrices in Action
- Create a matrix to represent a number
- Change the number from black to white
- Rotate the number

In [2]:
import numpy as np 

### Create a matrix to represent a number

In [4]:
#Create a matrix of image '1'
image_matrix = np.matrix([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]])
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [5]:
#Create a matrix with an image of a cross 
cross_matrix = np.matrix([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]])
print(cross_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### Invert the colors of the image 

In [9]:
rows = cross_matrix.shape[0]
columns = cross_matrix.shape[1]
print(rows, columns)

5 5


In [11]:
#Invert the cross 
for row in range(rows):
    for column in range(columns):
        if cross_matrix[row, column] == 0:
            cross_matrix[row, column] = 1
        else:
            cross_matrix[row, column] = 0

print(cross_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [12]:
#Invert the image of '1'
for row in range(rows):
    for column in range(columns):
        if image_matrix[row, column] == 0:
            image_matrix[row, column] = 1
        else:
            image_matrix[row, column] = 0

print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


### Rotate the number

In [13]:
#Transpose the image
print(image_matrix.T)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
#Flatten the matrix
print(image_matrix.flatten())

[[1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
